apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopstest
  template:
    metadata:
      labels:
        app: devopstest
    spec:
      containers:
        - name: devopstest
          image: devopstest-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
