apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopstest
  template:
    metadata:
      labels:
        app: devopstest
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: devopstestaksregistry
          image: devopstestaksregistry.azurecr.io/devopstest:latest
          ports:
            - containerPort: 8000
