apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopstest-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: devopstest.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devopstest-service
            port:
              number: 8000
